--- #YAML:1.0
name: Posy-Plugin-RandQuote
version: 0.42
author:
  - Kathryn Andersen
abstract: Posy plugin to give a random quote from a file.
license: perl
requires:
  Posy: 0.95
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::RandQuote:
    file: lib/Posy/Plugin/RandQuote.pm
    version: 0.42
generated_by: Module::Build version 0.261
